### PR TITLE
Example of std::function usage

### PR DESCRIPTION
**Pull request by BlackEdder**
Example of std::function usage as requested in #28.

### CODE REVIEW

**Comment by BlackEdder** [comment]
Note that this PR is against the testing branch.

**Comment by arkhipenko** [comment]
Hi Edwin,


Thank you.


Wow,. This is definitely different from all the code I wrote for Arduino.

And it's not that anything is wrong with it, it's all in my mind: the OO abstraction somehow always ends at the library level, and the sketches are always non-OO, with tasks and scheduler always created static and being very explicit.

I have not thought of encapsulating tasks inside another class.


One of the reasons is that effective scheduling could be achieved if [almost] nothing else is going on in the "loop()" (which is the case in your example, so no complaints).

The other reason was that callback methods of one task manipulated the execution parameters of other tasks, and therefore needed free access to all task objects running.

I will need to think long and hard how to use OO way you just introduced. But that's ok, thanks for your help.

Let me merge it and get testing.


Still planning to rename the callback types  [😊]


Regards,

Anatoli

'


________________________________

**Comment by arkhipenko** [comment]
ok. here is the first test result:

Arduino: 1.8.2 (Windows 10), Board: "Arduino/Genuino Uno"

In file included from C:\Users\anatoli\Documents\Arduino\libraries\TaskScheduler\examples\Scheduler_example15_STDFunction\Scheduler_example15_STDFunction.ino:6:0:

C:\Users\anatoli\Documents\Arduino\libraries\TaskScheduler\src/TaskScheduler.h:212:22: fatal error: functional: No such file or directory

 #include <functional>

                      ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


compiling for Arduino Uno. 

What am I doing wrong?

**Comment by arkhipenko** [comment]
Update: example 15 compiled successfully for ESP8266, but still does not compile for Arduino boards. Thoughts?

**Comment by BlackEdder** [comment]
I only ever tried it on the ESP8266. Looks like the standard arduino libraries don't include the functional header file at all. Sorry, I should have checked that.

**Comment by arkhipenko** [comment]
So we can limit this functionality to esp only, or find a way to include it into Arduino core (ourselves, or petition the Arduino dev team).

Is there a way to add this to Arduino core ourselves?


Sent from a mobile device. Apologies for accidental typos.


-------- Original message --------

**Comment by BlackEdder** [comment]
So on my machine functional is added from here:
```
$HOME/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/functional
```

I had a look at that header, but it also depends on multiple other includes (that might not be part of arduino libraries). Do you happen to know which toolchain arduino uses?

**Comment by arkhipenko** [comment]
On my linux box I have it in

$HOME/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2

Looks like you are using platform.io, and I still use the IDE

The arduino includes seem to be in this folder (I installed IDE into /opt): /opt/arduino/hardware/tools/avr/avr/include
and it seems to be considerably pruned (compared to the ESP8266 for sure: no c++ subfolder at all, much fewer .h files).

Looks like we'll have to limit the functionality to ESP boards only... I have already made the changes and testing.


________________________________

**Pull request merged**
