### PR TITLE
Make all method definitions inline

### PR DESCRIPTION
**Pull request by matthijskooijman**
This allows including TaskScheduler.h from multiple source files,
without causing multiple definition linker errors.

### CODE REVIEW

**Comment by adamryczkowski** [comment]
I like the simplicity of this solution.

**Comment by arkhipenko** [comment]
I am a bit concerned this might increase the sketch size if compiler decides to in-line "small" (by compiler's standards) methods, and the methods in question are frequently used.

I have a sketch which already barely fits into UNO, so that would be a good one to test with.

Will report back.


Sent from a mobile device. Apologies for accidental typos.






On Thu, Jul 7, 2016 at 8:03 AM -0400, "Adam Ryczkowski" <notifications@github.com> wrote:





I like the simplicity of this solution.

---

**Comment by adamryczkowski** [comment]
@arkhipenko Try my patch. It re-uses the code. It is both backward-compatible for single-file projects and includes example that uses handling multiple files as well.

**Comment by matthijskooijman** [comment]
The `inline` keyword doesn't actually tell the compiler to inline things. If the compiler has a function method available, it is eligible for inlining, if the compiler thinks the space/time tradeoff is worth it, regardless of the inline keyword (at least that's how I understand gcc implements it).

What the `inline` keyword does is change the linkage of a function such that, if multiple (identical?) definitions are present at link time, only one of them is used (as opposed to throwing a linker error, which is the default behaviour). Hence, the `inline` keyword allows putting a function implementation in a header file without causing linker errors, which again makes inlining possible. See also http://en.cppreference.com/w/cpp/language/inline

**Comment by matthijskooijman** [comment]
To confirm my theory, try compiling some examples with and without my patch applied, I expect they'll produce identical compiled code.

**Comment by arkhipenko** [comment]
Yep, that is what I was planning to do. Test your and Adam's solutions and pick one.


:)


Thanks for the update.


If not a secret, what are you using TaskScheduler for?




Sent from a mobile device. Apologies for accidental typos.






On Thu, Jul 7, 2016 at 8:39 AM -0400, "Matthijs Kooijman" <notifications@github.com> wrote:





To confirm my theory, try compiling some examples with and without my patch applied, I expect they'll produce identical compiled code.

---

**Comment by adamryczkowski** [comment]
Me - to control RGBW lights in the bathroom (incl. movement sensor and closed doors sensor). Lights need to dim smoothly - hence need for multitasking.

**Comment by matthijskooijman** [comment]
> If not a secret, what are you using TaskScheduler for?

A customer of mine is using it as port of the firmware for a 3D printer filament extruder (http://3devo.eu/).

**Comment by ricardojlrufino** [comment]
Any plans to integrate this version?

**Comment by arkhipenko** [comment]
Thinking about it. Did not have the time to compile all my sketches with this patch applied and check if a) they still work, and b) if size is not affected. I am pretty sure it is safe, but I have once spent the entire day chasing a bug in my sketch, which ended up being an "improvement" in the library. Have to test a lot after that all of my changes...

**Comment by arkhipenko** [comment]
Supported as of v2.2.0

**Comment by matthijskooijman** [comment]
Turns out there is a problem with this approach after all. The `iCurrentScheduler` globa variable is declared as static in the .h file, which causes a copy to appear in every compilation unit that includes the .h file. Because of this, `Scheduler::currentScheduler()` can return an invalid reference in some compilation units.

To fix this, you'd like to give this variable similar linkage to the inline functions, where it is included in multiple units, but merged together at link time. I believe there is a linkage for this, used for static variables in inline or template functions, though I'm not sure how to achieve such linkage on a normal variable. Just removing static is not sufficient, since then you will get linker errors (multiple definition). Adding extern fixes those, but requires a definition of the variable in a single .cpp file.

I've tried the latter approach (declaring extern in the .h file and add a .cpp file to define the variable), which works pretty well. Inside the .cpp file, the configuration macros are not available, so I've made the definition of the variable unconditional. This is not a perfect approach, but it should work well enough. Here's the commit https://github.com/arkhipenko/TaskScheduler/commit/907f20d6408de7eeaad0a2fa06588154fa271153 that implements it. I won't be preparing a PR, since our history diverged slightly with the manual merging of my previous PR and I won't be able to spend more time on this now.

**Comment by ActuallyRuben** [comment]
The current implementation in v2.2.0 still doesn't work with multi file projects. This is because the constructers weren't made inline. Regardless of that I advise to throw away the inline approach and either implement pull request #16 or #23.

**Pull request closed without merging**
