### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by tarzan115**
update readme.md base on origin file

### CODE REVIEW

**Comment by arkhipenko** [comment]
Oh boy. Thank you for all this work transforming the documentation for TaskScheduler into a real nice-looking Wiki! How do you use TaskScheduler if you don't mind me asking?

**Comment by tarzan115** [comment]
I am using and I trying to understand all your docs. so I think it better for the user if we have a document more reliable. 😄 
if I have more time. I want to transform your code to `cpp` files and `.h` files by split into 3 parts: `Task`, `Status Request` and `Task Scheduler`. It will more clearly for user and maintain bugs 😃   

thank you for your excellent library ❤️

**Comment by arkhipenko** [comment]
The best way to use the library is to code with it. Try to understand the examples. They are progressively more complex as they number goes up. Please don't be shy and ask questions - I owe you at least some answers for all the help you did.

Abount CPP - please do no waste you time doing it. THe reason everything is in the .H files is because otherwise you cannot use the #define compilation directives. This is just how Arduino IDE works, nothing we can do about it. If you look at the very early versions, that is how I had it, but had to put everything in one (now two) .H files.

**Comment by tarzan115** [comment]
okay, thank you for your library 😄

**Pull request merged**
